version: "3"

services:
  narou-predict:
    container_name: dev
    build :
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
    user: vscode
    depends_on: 
      - db

  db:
    container_name: db
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    env_file: ./db.env
    networks: 
      - default


volumes:
  node_modules:
