version: "3"

services:
  workspace:
    container_name: dev
    build :
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
    user: vscode